/** @type {import('prettier').Config } */
module.exports = {
  arrowParens: "avoid",
  jsxSingleQuote: false,
  singleQuote: false,
  trailingComma: "es5",
  bracketSpacing: true,
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  endOfLine: "lf",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(react-native/(.*)$)|^(react-native$)",
    "^(expo/(.*)$)|^(expo$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/types(.*)$",
    "^@/env(.*)$",
    "^@/types/(.*)$",
    "^@/constants/(.*)$",
    "^@/api/(.*)$",
    "^@/config/(.*)$",
    "^@/utils/(.*)$",
    "^@/index",
    "^@/reducers",
    "^@/slices/(.*)$",
    "^@/lib/(.*)$",
    "^@/helpers",
    "^@/hooks/(.*)$",
    "^@/screens/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "^@/assets/(.*)$",
    "^@/locales/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
}
